import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Use Turbopack (default in Next 16)
  // Supabase + Meta SDK need to be treated as ESM-compatible
  experimental: {
    // No server actions flag needed; we use route handlers + form posts
  },
  // Mark Supabase URL as a known env var so Next doesn't warn
  env: {
    SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  },
  // KIRK 2026-08-19: flipped ignoreBuildErrors to false. The original
  // reason (placeholder Supabase types in src/types/database.types.ts
  // breaking the strict prod build) was masking real type errors like
  // "X is not defined" — a page would deploy, render, then blow up at
  // runtime as ReferenceError when React hit the missing JSX identifier.
  //
  // The remaining tsc error is a stale generated file
  // (src/types/database.types.ts) — regenerated by
  //   npm run db:types
  // and not committed in CI. If the build fails because of that file,
  // either re-run the script or exclude it from tsconfig.
  //
  // The repo currently typechecks clean with `npx tsc --noEmit` (the
  // database.types.ts file is the only remaining issue). When it's
  // regenerated this flag stays off and the type checker is the
  // source of truth.
  typescript: {
    ignoreBuildErrors: false,
  },
  // (Next 16 removed the `eslint` config key — ESLint is now configured
  //  via `eslint.config.mjs` at the project root, or just not at all.)
  // Permanent redirects for the dashboard IA migration
  // (KIRK, 2026-08-16: ad-format-first nav — old /dashboard/{platform} URLs
  //  forward to /dashboard/{category}/{platform}).
  async redirects() {
    return [
      { source: "/dashboard/tiktok",  destination: "/dashboard/video-ads/tiktok",  permanent: true },
      { source: "/dashboard/youtube", destination: "/dashboard/video-ads/youtube", permanent: true },
    ];
  },
};

export default nextConfig;
